CREATE TABLE IF NOT EXISTS "mymarket_recent_searches" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mymarket_recent_searches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"term" varchar(255) NOT NULL,
	"user_id" varchar(255),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mymarket_recent_searches" ADD CONSTRAINT "mymarket_recent_searches_user_id_mymarket_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."mymarket_user"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
