CREATE TABLE IF NOT EXISTS "mymarket_conversations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mymarket_conversations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"buyer_id" varchar(255) NOT NULL,
	"seller_id" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mymarket_messages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mymarket_messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"conversation_id" integer NOT NULL,
	"sender_id" varchar(255) NOT NULL,
	"content" varchar(1000) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mymarket_conversations" ADD CONSTRAINT "mymarket_conversations_buyer_id_mymarket_user_id_fk" FOREIGN KEY ("buyer_id") REFERENCES "public"."mymarket_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mymarket_conversations" ADD CONSTRAINT "mymarket_conversations_seller_id_mymarket_user_id_fk" FOREIGN KEY ("seller_id") REFERENCES "public"."mymarket_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mymarket_messages" ADD CONSTRAINT "mymarket_messages_conversation_id_mymarket_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."mymarket_conversations"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mymarket_messages" ADD CONSTRAINT "mymarket_messages_sender_id_mymarket_user_id_fk" FOREIGN KEY ("sender_id") REFERENCES "public"."mymarket_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
